DOCKER_IMAGE_NAME := caching-by-squid
CONTAINER_NAME := caching-by-squid-testing

SRC_DIR := src
SRC_YML := $(wildcard $(SRC_DIR)/*.yml)

SQUID_FILES := squid/Dockerfile squid/entrypoint.sh $(wildcard squid/etc_squid/conf.d/*)

COMOPSE_HEADER := \#\n\# Do not edit this file directly. It is generated by Makefile.\n\#
COMPOSE_OPTIONS := --no-interpolate --no-path-resolution --no-normalize --no-env-resolution

BUILD_STAMP=tmp/.docker_build_done

ALL := $(BUILD_STAMP) compose.yml compose-xvlan.yml

ifdef BUILD_TIME_HTTP_PROXY
DOCKER_BUILD_ARGS += --build-arg HTTP_PROXY=$(BUILD_TIME_HTTP_PROXY)
endif


.PHONY: all clean  cache_clean build run

all: $(ALL)

clean:
	@echo "Cleaning the project..."
	docker image rm -f $(DOCKER_IMAGE_NAME):latest || true
	docker container rm -f $(CONTAINER_NAME) || true
	rm -f $(ALL)

cache_clean: clean
	docker buildx prune -f || true

build: $(BUILD_STAMP) compose.yml compose-xvlan.yml

$(BUILD_STAMP): $(SQUID_FILES)
	@echo "Building the Docker image on localhost..."
	echo "$(SQUID_FILES)"
	docker build \
		--progress=plain \
		$(DOCKER_BUILD_ARGS) \
		-t $(DOCKER_IMAGE_NAME):latest squid 2>&1 | tee tmp/build.log
	touch $(BUILD_STAMP)

run: build
	@echo "Running the Docker container..."
	docker run --rm -it \
		-p 3128:3128 \
		-p 3142:3142 \
		--env SQUID_HTTPS_USERS="${SQUID_HTTPS_USERS}" \
		$(DOCKER_IMAGE_NAME):latest


compose_run: build compose.yml compose-xvlan.yml
	@echo "Running the Docker container..."
	docker compose -f compose.yml up

compose.yml: $(SRC_YML)
	@echo "$(COMOPSE_HEADER)" > $@
	docker compose -f src/base.yml -f src/network-bridge.yml config $(COMPOSE_OPTIONS) >> $@

compose-xvlan.yml: $(SRC_YML)
	@echo "$(COMOPSE_HEADER)" > $@
	docker compose -f src/base.yml -f src/network-xvlan.yml config $(COMPOSE_OPTIONS) >> $@


test: build
	@echo "Running the test script..."
	docker stop $(CONTAINER_NAME) || true
	docker run --rm -it -d\
		-p 3128:3128 \
		-p 3142:3142 \
		--env SQUID_HTTPS_USERS="user1@password1" \
		--name $(CONTAINER_NAME) \
		$(DOCKER_IMAGE_NAME):latest
	sleep 5
	bash test.sh || { \
		echo "Tests failed." ; \
		docker stop $(CONTAINER_NAME) ; \
		exit 1; \
	};
	docker stop $(CONTAINER_NAME)

