
acl https_tmpl dstdomain HTTPS
http_access allow https_tmpl

acl test_host dstdomain get.docker.com
http_access allow test_host

acl test_host2 dstdomain apt.postgresql.org
http_access allow test_host2 port_80